return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 25,
  height = 25,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 5,
  nextobjectid = 112,
  properties = {
    ["spawnX"] = 13,
    ["spawnY"] = 16
  },
  tilesets = {
    {
      name = "tilesetv1",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "../graphics/tilesetv1.png",
      imagewidth = 80,
      imageheight = 80,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 25,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 25,
      height = 25,
      id = 1,
      name = "Layer1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        7, 7, 7, 7, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 7, 7,
        7, 7, 7, 8, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 6, 7,
        7, 7, 12, 13, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 6, 7,
        7, 13, 16, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 4, 4, 4, 4, 4, 4, 4, 11, 7,
        8, 18, 21, 23, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 4, 19, 19, 19, 19, 19, 4, 16, 6,
        8, 23, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 4, 19, 14, 4, 19, 19, 19, 19, 19, 4, 21, 6,
        8, 19, 19, 19, 14, 14, 14, 14, 14, 14, 14, 14, 19, 14, 19, 4, 19, 19, 19, 4, 19, 19, 4, 14, 6,
        8, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 19, 14, 19, 19, 19, 19, 19, 4, 19, 19, 14, 14, 6,
        8, 19, 19, 14, 19, 14, 14, 14, 14, 19, 1, 2, 2, 2, 3, 4, 14, 4, 4, 14, 19, 19, 14, 19, 6,
        8, 19, 19, 14, 19, 19, 19, 19, 14, 19, 6, 7, 7, 7, 8, 14, 14, 14, 14, 14, 19, 19, 19, 19, 6,
        8, 19, 19, 14, 19, 19, 14, 19, 14, 19, 6, 7, 7, 7, 8, 14, 14, 14, 14, 19, 19, 19, 19, 19, 6,
        8, 19, 19, 14, 19, 19, 14, 19, 14, 19, 11, 12, 12, 12, 13, 19, 19, 19, 19, 19, 4, 19, 19, 19, 6,
        8, 4, 14, 14, 19, 19, 14, 19, 19, 19, 16, 17, 17, 17, 18, 14, 14, 14, 19, 19, 19, 19, 19, 19, 6,
        7, 3, 19, 19, 14, 19, 14, 14, 19, 19, 21, 22, 22, 22, 23, 19, 19, 19, 19, 19, 19, 19, 19, 19, 6,
        7, 8, 19, 19, 14, 19, 19, 14, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 19, 19, 19, 19, 19, 6,
        7, 7, 3, 19, 14, 14, 19, 14, 14, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 19, 19, 19, 19, 19, 6,
        7, 7, 8, 19, 14, 19, 19, 14, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 19, 19, 19, 19, 19, 6,
        7, 7, 8, 19, 14, 14, 14, 14, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 19, 19, 1, 2, 2, 7,
        7, 7, 8, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 14, 1, 2, 7, 7, 12, 7,
        7, 7, 8, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 1, 2, 7, 7, 7, 13, 14, 6,
        7, 7, 7, 2, 2, 2, 2, 2, 2, 3, 19, 19, 19, 14, 14, 14, 14, 11, 12, 12, 12, 13, 14, 4, 6,
        7, 7, 7, 12, 12, 12, 12, 12, 12, 13, 19, 19, 19, 14, 14, 14, 14, 14, 14, 14, 14, 14, 19, 19, 6,
        7, 7, 13, 14, 14, 14, 14, 14, 14, 4, 19, 19, 19, 19, 19, 19, 19, 19, 4, 19, 19, 19, 19, 19, 6,
        7, 8, 14, 14, 14, 14, 14, 14, 14, 4, 19, 19, 19, 19, 19, 4, 19, 19, 19, 19, 19, 4, 19, 14, 6,
        7, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 14, 14, 14, 14, 14, 1, 7
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 160,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 48,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = -16,
          y = 208,
          width = 48,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 16,
          height = 144,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 48,
          width = 16,
          height = 48,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 32,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 0,
          width = 352,
          height = 48,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 48,
          width = 32,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 112,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 128,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 144,
          width = 64,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 128,
          width = 80,
          height = 96,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 320,
          width = 144,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 304,
          width = 96,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 288,
          width = 96,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 272,
          width = 64,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 304,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 128,
          width = 32,
          height = 144,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 320,
          width = 48,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 368,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 384,
          width = 368,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = -48,
          y = 352,
          width = 192,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 48,
          width = 16,
          height = 48,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 96,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 96,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 112,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 128,
          width = 16,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 128,
          width = 64,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 144,
          width = 16,
          height = 48,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 160,
          width = 16,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 208,
          width = 16,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 272,
          width = 48,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 208,
          width = 16,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 224,
          width = 16,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 192,
          width = 48,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Deaths",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 80,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 48,
          width = 16,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 48,
          width = 96,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 64,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 96,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 352,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 352,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 320,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 128,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Hints",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 352,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
