return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.12.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 25,
  height = 25,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 5,
  nextobjectid = 165,
  properties = {
    ["spawnX"] = 11,
    ["spawnY"] = 11
  },
  tilesets = {
    {
      name = "tilesetv1",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "../graphics/tilesetv1.png",
      imagewidth = 80,
      imageheight = 80,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 25,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 25,
      height = 25,
      id = 1,
      name = "Layer1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        7, 7, 7, 7, 12, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 8, 17, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 8, 22, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 8, 4, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 12, 12, 13, 19, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 7, 7, 7,
        8, 16, 17, 18, 19, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 11, 7, 7,
        8, 21, 22, 23, 19, 21, 22, 22, 1, 3, 22, 22, 22, 22, 22, 22, 22, 1, 3, 22, 22, 23, 16, 6, 7,
        8, 19, 19, 19, 19, 19, 19, 19, 11, 13, 14, 14, 19, 19, 19, 19, 19, 11, 13, 19, 19, 19, 21, 6, 7,
        8, 4, 19, 19, 19, 19, 19, 19, 16, 18, 19, 19, 14, 19, 19, 19, 4, 16, 18, 19, 19, 19, 19, 11, 7,
        8, 14, 4, 19, 19, 19, 19, 19, 16, 18, 19, 19, 19, 14, 19, 19, 4, 16, 18, 19, 19, 19, 19, 16, 6,
        8, 14, 14, 4, 19, 19, 19, 19, 16, 18, 19, 19, 19, 4, 19, 19, 14, 16, 18, 19, 19, 19, 19, 21, 11,
        8, 14, 14, 14, 4, 4, 19, 19, 16, 18, 19, 19, 19, 19, 19, 14, 19, 16, 18, 19, 4, 19, 4, 19, 16,
        8, 14, 14, 14, 14, 4, 19, 19, 16, 18, 19, 19, 19, 19, 14, 19, 19, 16, 18, 19, 19, 4, 19, 19, 21,
        8, 14, 14, 14, 14, 4, 19, 19, 16, 18, 19, 19, 19, 14, 19, 19, 19, 16, 18, 19, 19, 4, 19, 19, 14,
        8, 14, 14, 14, 14, 4, 19, 19, 16, 18, 19, 19, 14, 19, 19, 19, 19, 16, 18, 19, 19, 19, 19, 19, 14,
        7, 3, 14, 14, 14, 4, 19, 19, 16, 18, 19, 19, 19, 19, 19, 19, 19, 16, 18, 4, 19, 19, 19, 4, 14,
        7, 8, 14, 14, 14, 4, 19, 19, 16, 18, 4, 19, 19, 19, 19, 19, 19, 16, 18, 19, 19, 19, 19, 19, 1,
        7, 8, 14, 19, 19, 19, 19, 19, 16, 18, 14, 14, 14, 4, 19, 19, 19, 16, 18, 19, 19, 19, 19, 19, 6,
        7, 8, 4, 19, 19, 19, 19, 19, 21, 23, 19, 19, 19, 14, 14, 4, 19, 21, 23, 19, 19, 19, 19, 19, 6,
        7, 8, 4, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 4, 19, 4, 19, 19, 19, 19, 19, 1, 7,
        7, 8, 4, 4, 19, 19, 19, 19, 19, 4, 4, 4, 4, 4, 4, 4, 19, 4, 19, 19, 19, 19, 19, 6, 7,
        7, 8, 4, 4, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 4, 19, 19, 19, 19, 19, 6, 7,
        7, 8, 4, 4, 4, 4, 19, 19, 19, 4, 4, 4, 4, 4, 4, 4, 14, 4, 19, 19, 19, 19, 19, 6, 7,
        7, 8, 4, 4, 4, 4, 4, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 1, 7, 7,
        7, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "Walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 96,
          width = 32,
          height = 208,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 96,
          width = 32,
          height = 208,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = -48,
          width = 352,
          height = 160,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = -16,
          width = 64,
          height = 128,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 0,
          width = 16,
          height = 48,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = -64,
          y = 112,
          width = 80,
          height = 320,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 240,
          width = 16,
          height = 208,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 384,
          width = 432,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 368,
          width = 64,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 304,
          width = 48,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 176,
          width = 32,
          height = 128,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 112,
          width = 48,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 112,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 272,
          width = 48,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 288,
          width = 32,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 160,
          width = 16,
          height = 128,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 192,
          width = 32,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 144,
          width = 16,
          height = 96,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 352,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Deaths",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 288,
          width = 16,
          height = 96,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 352,
          width = 48,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 368,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 320,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 176,
          width = 16,
          height = 96,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 144,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 128,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 160,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 176,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 320,
          width = 112,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 288,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 304,
          width = 16,
          height = 64,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 352,
          width = 112,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 192,
          width = 16,
          height = 32,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 304,
          y = 240,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Hints",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 51,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 112,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 336,
          width = 16,
          height = 16,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
